In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp
import statsmodels.api as sm

In [2]:
mu, sigma = 0, 5 # mean and standard deviation of normal distribution for the error term
x = np.random.uniform(40,80,100)
epsilon = np.random.normal(mu,sigma,100)
y = 3 + 4*x + epsilon

In [3]:
model_reg = sm.OLS(y,x).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   1.000
Model:                            OLS   Adj. R-squared (uncentered):              1.000
Method:                 Least Squares   F-statistic:                          2.713e+05
Date:                Mon, 23 Sep 2024   Prob (F-statistic):                   5.28e-172
Time:                        13:42:36   Log-Likelihood:                         -296.91
No. Observations:                 100   AIC:                                      595.8
Df Residuals:                      99   BIC:                                      598.4
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             4.0548      0.008    520.878      0.000       4.039       4.070
==============================================================================
Omnibus:                        0.755   Durbin-Watson:                   1.831
Prob(Omnibus):                  0.686   Jarque-Bera (JB):                0.869
Skew:                          -0.184   Prob(JB):                        0.648
Kurtosis:                       2.730   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [4]:
# If the first column does not contain a constant numerical value(value=1) then an inetrcept won't be created
# Hence we added a constant to create an intercept
# The random error that the linear regression model produces is the epsilon (ε) symbol
x_updated = sm.add_constant(x)
model_updated = sm.OLS(y,x_updated).fit()
model_updated.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.990
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     9617.
Date:                Mon, 23 Sep 2024   Prob (F-statistic):           1.24e-99
Time:                        13:44:13   Log-Likelihood:                -294.77
No. Observations:                 100   AIC:                             593.5
Df Residuals:                      98   BIC:                             598.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.1026      2.464      2.071      0.041       0.212       9.993
x1             3.9725      0.041     98.065      0.000       3.892       4.053
==============================================================================
Omnibus:                        0.615   Durbin-Watson:                   1.853
Prob(Omnibus):                  0.735   Jarque-Bera (JB):                0.612
Skew:                          -0.181   Prob(JB):                        0.736
Kurtosis:                       2.877   Cond. No.                         322.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [5]:
# We now generate autocorrelated error terms
epsilon[0] = np.random.normal(mu,sigma,1)
for i in range(0,99):
    epsilon[i+1]=0.4*epsilon[i]+0.6*np.random.normal(mu,sigma,1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17388\4008544716.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  epsilon[0] = np.random.normal(mu,sigma,1)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17388\4008544716.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  epsilon[i+1]=0.4*epsilon[i]+0.6*np.random.normal(mu,sigma,1)


In [6]:
y = 3 + 4*x + epsilon
y

array([273.48593701, 274.34708832, 260.82189532, 256.9485346 ,
       248.12069492, 225.06367893, 306.92313123, 223.91908756,
       215.8266444 , 303.74986532, 258.36448878, 242.26269234,
       299.17957863, 237.25913813, 203.51262874, 289.230802  ,
       281.10212041, 258.74395013, 317.89334287, 314.33166052,
       265.05403437, 251.94744999, 166.32887624, 317.2395088 ,
       278.79437245, 245.78093916, 301.73288175, 267.09062206,
       248.0332564 , 211.28303849, 312.27028657, 245.02555128,
       268.920942  , 165.77963901, 170.04289468, 191.39864842,
       234.94008038, 254.60709775, 278.10306619, 316.29664642,
       217.70417317, 236.87632555, 284.77371626, 160.89271959,
       289.60164159, 253.45799608, 277.86530422, 317.2814852 ,
       204.14179448, 218.0105224 , 254.93061796, 287.92448348,
       304.17284622, 162.64050801, 212.20927816, 221.172761  ,
       244.64056046, 213.73018363, 294.93344348, 216.0722739 ,
       177.37199297, 224.1761949 , 227.05947707, 250.07

In [7]:
x_updated = sm.add_constant(x)
model_OLS = sm.OLS(y,x_updated).fit()
model_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                 1.840e+04
Date:                Mon, 23 Sep 2024   Prob (F-statistic):          2.41e-113
Time:                        14:02:41   Log-Likelihood:                -262.54
No. Observations:                 100   AIC:                             529.1
Df Residuals:                      98   BIC:                             534.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.5310      1.785      2.538      0.013       0.988       8.074
x1             3.9814      0.029    135.662      0.000       3.923       4.040
==============================================================================
Omnibus:                        1.500   Durbin-Watson:                   1.331
Prob(Omnibus):                  0.472   Jarque-Bera (JB):                1.128
Skew:                          -0.254   Prob(JB):                        0.569
Kurtosis:                       3.113   Cond. No.                         322.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [8]:
from scipy.linalg import toeplitz
toeplitz(np.array([1,0.5,0,0,0,0,0,0]))

array([[1. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 1. , 0.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.5, 1. , 0.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 1. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 1. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.5, 1. , 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.5, 1. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.5, 1. ]])

In [9]:
rho = 0.4
cov_matrix = sigma**2*toeplitz(np.append([1,rho],np.zeros(98)))
sm.GLS(y,x_updated,cov_matrix).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            GLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.996
Model:                            GLS   Adj. R-squared:                  0.996
Method:                 Least Squares   F-statistic:                 2.495e+04
Date:                Mon, 23 Sep 2024   Prob (F-statistic):          8.71e-120
Time:                        14:06:41   Log-Likelihood:                -257.15
No. Observations:                 100   AIC:                             518.3
Df Residuals:                      98   BIC:                             523.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.6812      1.567      4.264      0.000       3.572       9.791
x1             3.9458      0.025    157.941      0.000       3.896       3.995
==============================================================================
Omnibus:                        0.009   Durbin-Watson:                   2.221
Prob(Omnibus):                  0.996   Jarque-Bera (JB):                0.082
Skew:                           0.022   Prob(JB):                        0.960
Kurtosis:                       2.866   Cond. No.                         206.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
np.append([1,rho],np.zeros(98))

array([1. , 0.4, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])